full address:s:HOST[: 129.222.187.9]
username:karlcollins306-afk
screen mode id:i:2
desktopwidth:i:1920
desktopheight:i:1080
session bpp:i:32
audiomode:i:0
redirectclipboard:i:1
redirectprinters:i:1
redirectdrives:i:0
enablecredsspsupport:i:1
prompt for credentials on client:i:1
authentication level:i:2
compression:i:1
use multimon:i:0

screen mode id:i:2
desktopwidth:i:1920
desktopheight:i:1080
session bpp:i:32
audiomode:i:0
redirectclipboard:i:1
redirectprinters:i:1
redirectdrives:i:0
enablecredsspsupport:i:1
prompt for credentials on client:i:1
authentication level:i:2
compression:i:1
use multimon:i:0

